export default function Articles(){
    return [
        {
            'Title': 'What to do with VAR?',
            'Date': 'Tue 15th December 2020',
            'Text': '<div>Most people agree that VAR as it currently stands, needs to change. Peoples issues with it do vary, for some people it is the speed, for some its about when to interject or not, some believe it is the laws of the game that need to change to become more VAR friendly.<br/><br/>Technology obviously has its place in football. Goal line technology, one large blip aside, has been perfect since the day it was introduced. The nature of the decision lends itself to technology, it is a clear-cut decision of whether the ball has crossed the line or not. Offsides should be exactly the same. It should be a clear-cut decision, is one player in front of another. The issue I take with VAR is not in its application but the technology itself. It is the technology that is not good enough. For me, it is about the quality of cameras. The zoom of the cameras is not of sufficient quality and neither is the number of frames per second. If they were good enough, with the correct angles, VAR officials could actually make accurate calls about when the ball was kicked and about whether one player was in front of another. Let us be clear, the drawing of their lines is nothing more than a façade, providing not much more than just an illusion of genuine accuracy.<br/><br/>This also applies to penalty and red card decisions. VAR officials, as it stands, do not have the right tools to make the decisions they are being asked to. They are forced to watch replays five or six times without being able to slow it down enough or zoom in enough, whilst maintaining the quality of picture. Even five or six replays is often not enough to tell if a player got the ball or to tell if there was contact.<br/><br/>There should be no need for the match referee to go to the pitch side monitor. The VAR official is equally qualified, and in a nice warm studio without half as much pressure, should be in a far better position to make the decision at a speed that does not detract as much excitement from the game. There will always be judgment calls too, for those decisions that are not ever going to be clear cut, VAR cannot solve them. But with better technology, it can aid referees in making those judgement calls, they are both used to and remarkably good at making those opinionated calls.<br/><br/>So that is my conclusion, improve the technology to help the officials out. The Premier League has all the money in the world so its more than possible, and certainly worth it to allow quicker, more precise decisions.</div>',
            'Tease': 'VAR has to change, but clearly it has potential, so what can be done to make it work?',
            'Image': 'lino.jpg'
        },
        {
            'Title': 'Is International Football Dead?',
            'Date': 'Mon 14th December 2020',
            'Text': '<div>The conclusion of the latest international football break was met with jubilation from football fans and pundits alike. Social media was inundated with posts and memes celebrating that club football was returning, uninterrupted, until March.<br/><br/>The clear resentment of international breaks is a stark contrast from the outpouring of emotion we see from football fans when a major tournament comes around. The euphoria across the country when England reached the semi final of the world cup back in 2018 is testament to the fact there is still a huge appetite for international football.<br/><br/>This is obviously not a new problem. This is exactly what the nations league was brought in for, and in almost every way its exactly what was needed; a series of competitive games with something to play for. But its not quite hit the mark, maybe that suggests there is no solution.<br/><br/>But perhaps there is a solution, one that involves scrapping international breaks in favour of uninterrupted club football. With a slightly shorter regular season, all international football could take place every other summer. The passion and appetite would still be there. An expanded European championships, plus equivalents, and an intense intra-continental qualification process to proceed the world cup, present a couple of opportunities for this to work.</div>',
            'Tease': 'Everyone seemed to be happy to see the back of international football for a while, so is international football dead, and if so, can it be brought back to life?',
            'Image': 'wembley.jpg'
        },
        {
            'Title': 'League Two Predictions!',
            'Date': 'Wed 30th September 2020',
            'Text': '<div>This season’s league two looks to be wide open with any team who has a good season having a big chance of promotion.<br><br>One of those teams who look as though things maybe clicking into place is my pick for the top spot, Cambridge United. The squad have been moving in the right direction over the last few seasons and I believe now could be their time. I think the same story holds for my tip for second spot Newport County. They had a great season in 18/19 but seem to suffer a hangover from the playoffs last season. This year could well see them back to the form that saw them make the playoffs the year before last. In the third and final automatic promotion spot I have Salford City who look to have added to their squad again this season which should give them just enough to have a good year. The four playoff spots are really up for grabs but my picks are Colchester, Bradford, Exeter and Cheltenham. Three of whom made the playoffs last season, hopefully one of them will go one step further this year.<br><br>My two tips for relegation are the hapless Southend United and league two new boys Barrow. Unfortunately Southend appear to be in such a mess that the only place I can see them finishing this season is bottom. Barrow look to be continuing to play the lovely brand of football that saw them promoted last season even though they now have a new manager. However, I just don’t think they will have enough to stay up even though I would think most neutrals will be rooting for them. The lifeline for these two though this season is the current financial situation all the clubs now find themselves in. Who knows what may happen.<br><br>Good luck to all.<br><br>1. Cambridge United<br>2. Newport County<br>3. Salford City<br>4. Colchester United<br>5. Bradford City<br>6. Exeter City<br>7. Cheltenham Town<br>...<br>23. Barrow<br>24. Southend United</div>',
            'Tease': 'The final post of the series; League two predictions! A look at which teams will rise up the pyramid and which will be exiled to the national league.',
            'Image': 'goal.jpg'
        },
        {
            'Title': 'League One Predictions!',
            'Date': 'Wed 30th September 2020',
            'Text': '<div>This season’s league one looks as though it will be one of the hardest fought for sometime with a number of historically big sides fighting for promotion.<br><br>My tip for the title is Hull City, the only one of the three relegated teams not to be under or looking for new ownership. In the second and final automatic promotion spot I have an Ipswich Town side who now look to be better organised under Paul Lambert. In third spot I have a Sunderland side who finally look to have got it right this year and will, I predict, win the playoffs. Oxford, who are now settling down after the disappointment of last season’s playoffs, Charlton, who will be up there mainly due to the destined for bigger things Manager Lee Bowyer and Fleetwood with Joey Barton completing the playoff spots.<br><br>At the bottom I have Bristol Rovers. Their form in the early part of this season has unfortunately been poor following on from the equally poor end to last season and at the moment I can’t see a way out of it for them. Bottom but one I have a Rochdale side who have lost the goals of former striker Ian Henderson which looks like it might cost them this season. Just above the bottom two I have an M K Dons side with Accrington Stanley completing the bottom four.<br><br>League one this season feels a bit split into two with half the league looking for promotion and half fighting against relegation with few teams looking at mid table. Good luck to all.<br><br>1. Hull City<br>2. Ipswich Town<br>3. Sunderland<br>4. Oxford United<br>5. Charlton Athletic<br>6. Fleetwood Town<br>...<br>21. Accrington Stanley<br>22. MK Dons<br>23. Rochdale<br>24. Bristol Rovers</div>',
            'Tease': 'A look at which League one teams will be playing their football in the Championship next year, and which four teams are facing the drop.',
            'Image': 'seats.jpg'
        },
        {
            'Title': 'Championship Predictions!',
            'Date': 'Wed 30th September 2020',
            'Text': '<div>So the Championship this season will be wide open with a number of teams thinking this will be their year.<br><br>Even with a new inexperienced Manager I think the title will go to Bournemouth who have kept enough quality in their squad to bounce back to the Premier league at the first time of asking. More of a surprise will be the resurgence of a Reading side who have added to the squad wisely and look to be gelling nicely and, I believe, will take the second automatic promotion spot. In a close third position I have gone for a Swansea side who may well run the top two close. The rest of the playoff positions should go to Watford, Norwich and a Birmingham side who look to be getting it right for once this year.<br><br>At the bottom unfortunately I can’t see past a Wycombe side who will hopefully enjoy their one season in the Championship. Bottom but one I have a Rotherham team who have turned into a bit of a yo-yo side over the last few years which I believe looks likely to continue again this season. Finally I think the points deduction will be just too much for Sheffield Wednesday but they won’t go down without a fight.<br><br>Once again the Championship will be an exciting league and will go down to the wire. Good luck to all the teams.<br><br>1. AFC Bournemouth<br>2. Reading<br>3. Swansea<br>4. Watford <br>5. Norwich City<br>6. Birmingham City<br>...<br>22. Sheffield Wednesday<br>23. Rotherham<br>24. Wycombe Wanderers</div>',
            'Tease': 'Who will top the Championship this year? Who will earn themselves a place in next years Premier league and who will face relegation to league one?',
            'Image': 'stadium.jpg'
        },
        {
            'Title': 'Premier League Predictions!',
            'Date': 'Thu 24st September 2020',
            'Text': '<div>1. Man City<br>2. Liverpool<br>3. Chelsea<br>4. Man United<br>5. Arsenal<br>6. Tottenham<br>7. Everton<br>8. Leicester<br>9. Wolves<br>10. Newcastle<br>11. Crystal Palace<br>12. Leeds<br>13. Southampton<br>14. Brighton<br>15. Burnley<br>16. Sheffield United<br>17. Aston Villa<br>18. West Ham<br>19. Fulham<br> 20. West Brom<br><br>Although Liverpools late additions are a promising sign, I think it will be Man City who are crowned champions this year. Chelsea will be strong and threatening with all of their new signings but will not be ready this year to challenge the top two. I think it will be Man United that will occupy fourth position if they can make one big signing before the window closes. I predict Jose Mourinho to fail to deliver Champions League football for Tottenham this year, and to fair no better in his quest for a trophy.<br><br>Ancelotti\'s go-to man, James Rodriquez, already looks to be a great signing for Everton, I predict Ancelotti will do wonders for Everton this year and wouldn\'t even be suprised if they broke into the top 6.<br><br>Leeds are the only promoted side I am tipping to stay up, however, I am not getting as carried away as some people, my predicted twelth is the very highest I can see them finishing.<br><br>Aston Villa will again be in a relegation battle, I predict that again, they will just miss the drop.<br><br>The three teams I have predicted to get relegated will not be a shock. West Ham\'s problems have been widely publicised. As has the general concensus that West Brom and Fulham have not shown the appetite in the transfer window that is needed to turn a good Championship side into a side that can kick-on in the Premier league. </div>',
            'Tease': 'My premier league predictions for the 2020-2021 season! Will Liverpool retain their crown and just how high can Leeds finish in their first season back in the Premier league?',
            'Image': 'corner.jpg'
        },
        {
            'Title': 'Too soon for Thiago?',
            'Date': 'Mon 21st September 2020',
            'Text': '<div>Interesting to see the rave reviews for Thiago Alcantara this weekend. Obviously his passing was exceptional against a side who were struggling with 10 men but the tackle to give away the penalty was poor to say the least.<br><br>It reminded me of when Fabinho arrived at Liverpool and was caught out by the speed and aggression of the Premier league.<br><br>We have seen over many years now that very few players even of the pedigree of Thiago can come to England and hit the ground running. However, given time, if Thiago settles down and reaches anywhere near the level reached by Fabinho, then Liverpool will have yet another world class player In their midst.<br><br>I will be surprised though if Klopp relies heavily on Thiago this side of Christmas. Klopp is the master of integrating new players slowly as we have seen with Fabinho and more recently with the recent progression of Naby Keita, patience is definitely the way to go, a lesson that Frank Lampard will need to take notice of with his new recruits at Chelsea. Unfortunately for him though time is not something that is historically forthcoming with a more impatient Abramovich led Chelsea.</div>',
            'Tease': 'Thiago has received a lot of plaudits for his first 45 mins in a Liverpool shirt, but are Liverpool fans getting ahead of themselves?',
            'Image': 'anfield_3.jpg'
        },
        {
            'Title': 'Final day predictions!',
            'Date': 'Sun 26th July 2020',
            'Text': '<div>The end of the premier league season is finally here, and although the race for the tittle has been over for the majority of the season there is much still to play for. Champions league, Europa league and survival in the premier league hangs in the balance for many teams going into the final day. The fixtures couldn’t have been planed any better. 3rd plays 5th and 4th plays 6th.<br><br>The game I’m sure most people will choose to tune into will be Man United vs Leicester. With a three-way battle for the two remaining champions league places and just one point between them it’s a winner takes all game, while a point could be enough for Leicester it is enough for Man United. In the other game Chelsea take on 6th place Wolves. Chelsea only need a point to secure champions league football while Wolves also need a win to secure European football.<br><br>My predictions: a win for United and a win for Chelsea. Although inconsistent, Man United have shown some real quality in recent games. If their goal keeper and defence can just keep it together for one final game they should have more than enough attacking threat to secure champions league football. Chelsea must be encouraged by their transfer activity and feel optimistic about next season but they might hit a wall in the transfer window if they miss out on the champions league football. They can be excused for loosing to Liverpool and similarly have shown flashes of quality in recent weeks that bodes well for this important game and for next season.<br><br>The battle to avoid relegation is also well and truly on. Norwich are down, Bournemouth, Watford and Aston Villa are the teams still fighting. Bournemouth would need some real good fortune, they must win and both others lose. Their chances of beating Everton are reasonable but their chances of survival are slim. Watford are the other team I predict to be playing football in the championship next year.<br><br>Aston Villa remarkably as probably the poorest team of the three have the best chance of winning. Their opposition, West Ham, have nothing to play for and are another team lacking quality. Watford would need to better Villas result, if Villa win Watford will need to beat Arsenal by 2 goals more than Villa have won by.<br><br>If Aston Villa stay up they must really think themselves lucky, having spent all that money with little to show for it. If they get a second chance, they must learn from their mistakes. Perhaps the team that survives can look to the other two for reinforcements for next year. Callum Wilson is the pick of the bunch of players that are far too good for the championship. If Wilson can stay fit again next year he would be a fantastic addition to the vast majority of premier league sides.</div>',
            'Tease': 'There is a lot left to play for going into the last day, who will secure survival and who will be playing europena football next year?',
            'Image': 'old_trafford.jpg'
        },
        {
            'Title': 'Money or Club?',
            'Date': 'Mon 14th July 2020',
            'Text': 'With the current situation unfolding at Wigan Athletic, the question is, are we starting to see a trend of owners using the clubs for financial gain with no interest as to whether the teams remain in existence or not? With rumours around the unbelievably quick take over and move into administration of Wigan and with the talk of betting scams etc being possibly behind the very strange goings on. Plus the issues that Bury had with an owner, who seemed possibly motivated more by the financial gains than by the best interests of the club. The clear trend is for the owners who have no interest in football, to be cashing in. I am sure with the F.A. looking into the Wigan situation, they will hopefully put something in place to prevent this sort of thing reoccurring. Maybe a similar thing to the German system where the owners place a bond with the league would help. Either way we will need to keep an eye on this very worrying trend, otherwise, as always, the fans and the local community will be the ones to suffer. We don’t want to end up losing more teams and with talk of wage caps for the lower leagues which will again be increasing the gap between the so called bigger clubs and the others, we could be diving head first into the Premier league one and two setup that has been suggested more than once. This would then lead to the demise of our current beloved four division setup and may even pave the way for the European league that the rest of Europe seem hell bent on moving too.',
            'Tease': 'Are football club owners just involved for the money? Where does that leave us fans and local communities?',
            'Image': 'football_fans.jpg'
        },
        {
            'Title': 'Teams in trouble',
            'Date': 'Tue 7th July 2020',
            'Text': 'With only a handful of games left in the season it looks as though the three teams going down this season will be Norwich, Aston Villa and Bournemouth. Watford could of course replace one of the three but I believe they will have enough to beat the drop. So looking at Norwich, although they are a good footballing side they have just lacked that bit of quality this season that would have kept them up. Next season however will be a different story with most of the current squad staying with the club, the goals of Teemu Pukki and the emergence of Todd Cantwell will almost certainly see the side from Norfolk bounce straight back to the Premier League at the first time of asking. Aston Villa on the other hand gained promotion last season via the playoffs and this season have missed the goals of former Chelsea loanee, Tammy Abraham and for much of this year, the work rate of the just returning from injury, central midfielder, John McGinn. Next season will almost certainly see the departure of Captain and local lad Jack Grealish so unless the money for Jack is reinvested or the owners decide to make a reasonable size transfer kitty available, I cannot see an instant return to the big time for the Midland club. Bournemouth are the surprise team of the three facing the drop. A team that have been in the Premier league now for five consecutive seasons. For some reason they have lost their way and appear to have stagnated somewhat under Manager Eddie Howe. The question is should the club look to freshen things up with a new Manager or does Mr Howe deserve the opportunity to bring the South coast side straight back up from the Championship. Certainly you would think he should be given the first half of the season as a minimum to turn things round but it certainly looks like one or two new faces will be needed if the club is to return to the Premier league at the first time of asking.',
            'Tease': 'With only a handful of games left in the season we take a look at what relegation could mean for the few clubs in danger...',
            'Image': 'villa.jpg'
        },
        {
            'Title': 'Man City vs Liverpool',
            'Date': 'Thu 2nd July 2020',
            'Text': 'Tonight, the newly crowned English Champions take on Manchester city. A match now unimportant in the context of this season, but a match with huge potential repercussions for the record books and for what it could symbolise going forward in the Klopp-Guardiola era. Coming back for their first game after securing the title we should expect Klopp to try and harness that positive energy into an energetic performance where Liverpool really try and get at Man City’s questionable defence. They will look to go out, all guns blazing, to try and overwhelm their opposition into allowing them to control the game. There has to be real questions about whether they will be able to pull that off after the week they have had. A night of celebrations turned into a couple of days which resulted in delaying their preparations for tonight’s match. Liverpool’s motivation cannot be the same as it would have been had these three points on offer been the ones that secured them the elusive tittle. A lack-lustre hangover seems very plausible. Since the premier league resumed Man City have come back in the same vein that they had maintained all season, too much inconsistency and a defence they simply cannot depend upon when they are called into action. It seems inevitable that tonight’s result will therefore be dependent on whether Man City’s defence will need to be relied upon. Guardiola will not struggle to instil some motivation in his players tonight. The urge to claim back some air of the dominance they had prior to this season, to ruin the party. Man City will be determined to re-assert themselves ahead of next season. Should Liverpool win tonight there is a good chance they will go on to beat Man City’s records, the most points in a season, the most wins in a season and the biggest winning margin. But the real importance of this match for both teams is not the records but what it could signify for next season. Are Liverpool entering into a period of dominance or will they resume their inconsistent ways of the past? On many occasions in this immaculate season has that inconsistency threatened to slip back into play. A strong performance tonight from Man City can go a long way towards refuting the ideas that their team is just a shadow of what it was two years ago and that despite their consistently extravagant spending that there are fundamental shortcomings in their squad.',
            'Tease': 'A look at what\'s left to play for ahead of Man City vs Liverpool...',
            'Image': 'anfield_2.jpg'
        },
        {
            'Title': 'What now for the champions',
            'Date': 'Sun 28th June 2020',
            'Text': 'After Liverpool’s dominance this season what will Herr Klopp do next? Watching the recent Merseyside derby highlighted a couple of areas that need to be strengthened. Left back seems to be a problem when Andy Robertson isn’t fit with James Milner filling in on most occasions. Whilst Milner does an ok job there he is no left back, maybe a left back who can also play centre back would be a good option as the middle of defence is also a bit of an issue. Obviously Virgil Van Dijk is the first choice but who plays along side him? Joel Matip has been the pick of the bunch this season closely followed by Joe Gomez but both appear to be injury prone and although Dejan Lovren has been a great servant to the club, he is not at the level of the other three. I have heard rumours that the club have been linked to Napoli’s Kalidou Koulibaly who would be a very exciting addition, the alternative is to bring through Sepp van den Berg who looks a very good prospect but it could be a little too early for the 18 year old. The other issue is when one of the front three are missing. Particularly on the right side when Salah isn’t playing, they miss the link up, movement and scoring Mo provides. The club have clearly been searching for the answer to this in recent transfer windows but the likes of Shaqiri, Minamino and Keita have yet to prove themselves as the solutions to the problems. Again the best option to the issues maybe the emergence of young talent with the likes of Harvey Elliott and Curtis Jones showing glimpses of what are hopefully very bright futures for the pair. One other young player that deserves a mention is right back Neco Williams who also looks as though he will be putting pressure on yet another young but already superstar player Trent Alexander-Arnold. I’m sure Jurgen will be on the case but it looks to me that the answers may already be in place for a very bright present and future.',
            'Tease': 'What\'s next for Jurgen Klopp and his Liverpool side, there are a couple of areas in particular that need attention...',
            'Image': 'liverpool_fans.jpg'
        },
        {
            'Title': 'Henderson At A Crossroads',
            'Date': 'Tue 23rd June 2020',
            'Text': 'So after nearly 3 full seasons in league football Dean Henderson has come to a crossroads in his career. Should he stay with Man Utd and try to disposes David De Gea of the No.1 shirt or should he move on to further his career. After seeing him play for a season with Shrewsbury Town in league 1 and a season in the Championship with Sheff Utd it was inevitable that he would be a star in the Premier league. Admittedly he will need some assurances from Mr Solskjaer but surely with the errors that are creeping in to De Gea’s games it is time for Man Utd to cash in and go with Deano. Although Roy Keane\'s rantings about De Gea on Sky were exaggerated for TV I can see where he is coming from and their was definitely some truth in his outburst. The 23 year old Henderson is only going to get better whilst De Gea has stagnated and only time will tell but in my opinion Deano will become the better keeper of the two and will be England’s No.1 for many years to come. So come on Ole give him a go.',
            'Tease': 'A look at the decision facing Man United regarding what to do with in-form goalkeeper Dean Henderson and out of form David De Gea...',
            'Image': 'sheffield.jpg'
        },
        
    ]

}